---
deployment:
  tasks:
    - export DEPLOYPATH=/home/millxewk/hub.millie.moe
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R fonts $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R less $DEPLOYPATH
    - /bin/cp -R resources $DEPLOYPATH
    - /bin/cp -R script $DEPLOYPATH