// All the variable for the app
// Their names are explicit

var username = "Emilia";
var kanji = "ミリー";
var images = [
  "01.png",
  "02.png",
  "03.png",
  "04.png",
  "05.png",
  "06.png",
  "07.png",
  "08.png",
  "09.png",
  "10.png",
  "11.png",
  "12.png",
  "13.png",
  "14.png",
  "15.png",
  "16.png",
  "17.png",
  "18.png",
  "19.png",
  "20.png",
  "21.png",
  "22.png",
  "23.png",
  "24.png",
  "25.png",
  "26.png",
  "27.png",
  "28.png",
  "29.png",
  "30.png",
  "31.png",
  "32.png",
  "33.png",
  "34.png",
  "35.png",
  "36.png",
  "37.png",
  "38.png",
  "39.png",
  "40.png",
  "41.png",
  /*
  "42.png",
  "43.png",
  "44.png",
  "45.png",
  "46.png",
  "47.png",
  "48.png",
  "49.png",
  "50.png",
  "51.png",
  "52.png",
  "53.png",
  "54.png",
  "55.png",
  "56.png",
  "57.png",
  "58.png",
  "59.png",
  "60.png",
  "61.png",
  "62.png",
  "63.png",
  "64.png",
  "65.png",
  "66.png",
  "67.png",
  "68.png",
  "69.png",
  "70.png",
  "71.png",
  "72.png",
  "73.png",
  "74.png",
  "75.png", 
  */
];
var searchs = [
  ["!g", "https://www.google.com/search?q="],
  ["!d", "https://duckduckgo.com/?q="],
  ["!u", "https://"],
  ["!b", "https://danbooru.donmai.us/posts?tags="],
  ["!s", "https://saucenao.com/search.php?url="],
];
var favorites = [
  [ "しゃかいてき"+"<br>"+"Social",
    [
      ["4chan" , "https://boards.4channel.org/w/catalog", ""],
      ["twitter" , "https://twitter.com/home", ""],
      ["steam" , "https://steamcommunity.com/id/lewd-/home/", ""],
      ["reddit" , "https://www.reddit.com/", ""],
      ["gmail" , "https://mail.google.com/", ""],
    ]
  ],
  [ "ショッピング"+"<br>"+"Shopping",
    [
      ["amazon" , "https://smile.amazon.com/", ""],
      ["ebay" , "https://www.ebay.com/", ""],
      ["etsy" , "https://www.etsy.com/" , ""],
      //["aliexpress" , "https://www.aliexpress.com/" , ""],
      ["isthereanydeal" , "https://isthereanydeal.com/", ""],
      ["fasttech" , "https://www.fasttech.com/", ""],
      ["3fvape" , "https://www.3fvape.com/", ""]
    ]
  ],
  [ "トラッカー"+"<br>"+"Trackers",
    [
      ["animez", "https://animetorrents.me/", ""],
      ["pornbay", "https://pornbay.org/index.php", ""],
      ["torrentleech", "https://www.torrentleech.org", ""],
      ["privatehd", "https://privatehd.to/", ""],
      ["blutopia", "https://blutopia.xyz/", ""],
      //["dxdhd", "https://dxdhd.com/", ""],
      //["digitalcore", "https://digitalcore.club/", ""],
      ["myanonamouse", "https://www.myanonamouse.net/", ""],
    ]
  ],
  [ "ゲーミング"+"<br>"+"Gaming",
    [
      ["steammatch", "https://www.steamtradematcher.com/", ""],
      ["exophase", "https://www.exophase.com/user/Milky/", ""],
      ["steamhunters", "https://steamhunters.com/id/lewd-/games", ""],
      ["completionist.me", "https://completionist.me/", ""],
      //["nexusmods", "https://www.nexusmods.com/skyrimspecialedition", ""],
      //["gbatemp", "https://gbatemp.net/forums/", ""],
    ]
  ],
  [ "ビデオ"+"<br>"+"Video",
    [
      ["plex", "https://app.plex.tv/desktop", ""],
      ["myanimelist", "https://myanimelist.net/", ""],
      ["youtube", "https://www.youtube.com/feed/subscriptions", ""],
      ["twitch", "https://www.twitch.tv/", ""],
    ]
  ],
  [ "その他"+"<br>"+"Others",
    [
      ["myfigurecollection" , "https://myfigurecollection.net/" , ""],
      ["voice", "https://app.genderfluentapp.com/", ""],
      ["flipper", "https://flipper-xtre.me/", ""],
      ["saucenao" , "https://saucenao.com/", ""]
    ]
  ]
];

